# Pre-commit hooks for Methodical Cloud website
# TypeScript/JS quality + AI reference blocking

repos:
  # Basic file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(package-lock\.json|\.next/)'
      - id: end-of-file-fixer
        exclude: '^(package-lock\.json|\.next/)'
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-json
        exclude: '^(package-lock\.json|tsconfig\.json)'
      - id: check-yaml

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: '^(node_modules/|\.next/)'

  # TypeScript/JavaScript formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]
        exclude: '^(package-lock\.json|\.next/|node_modules/)'

  # ESLint
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'npx eslint --fix "$@" || true' --
        language: system
        types_or: [javascript, jsx, ts, tsx]
        exclude: '^(node_modules/|\.next/)'

  # CRITICAL: Block AI tool references in commit messages
  - repo: local
    hooks:
      - id: check-commit-message
        name: check-commit-message
        entry: .pre-commit-hooks/check-commit-message.py
        language: script
        stages: [commit-msg]
        pass_filenames: true
        always_run: true

fail_fast: false
default_stages: [pre-commit]
