baseURL = "https://methodicalcloud.com/"
title = "Methodical Cloud"
languageCode = "en-us"

[permalinks]
blog = "/blog/:slug/"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "podcast"
name = "Podcast"
url = "/podcast/"
weight = 3
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
