baseURL = "https://methodicalcloud.com/"
title = "Methodical Cloud"
languageCode = "en-us"
enableRobotsTXT = true

# Add basic site parameters
[params]
description = "Clarity in automation, systems that scale, and technical storytelling that doesn’t suck"
author = "Larry Smith Jr."
email = "hello@methodicalcloud.com"

# SEO enhancements  
[params.seo]
# Open Graph
og_image = "/images/og-default.jpg"

[permalinks]
blog = "/blog/:slug/"
podcast = "/podcast/:slug/"

# Set up taxonomies
[taxonomies]
tag = "tags"
category = "categories"

# Add RSS feed support
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

# Enable syntax highlighting
[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = "monokai"

# Keep your existing menu
[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "podcast"
name = "Podcast"
url = "/podcast/"
weight = 3
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
